import { getSurahPath } from '@/lib/surah-meta';

export type LearningPlan = {
  slug: string;
  title: string;
  summary: string;
  days: number;
  surahNumber?: number;
  searchQuery?: string;
  imageTone: string; // tailwind gradient
  featured?: boolean;
};

/** Curated plans inspired by https://quran.com/learning-plans */
export const LEARNING_PLANS: LearningPlan[] = [
  {
    slug: 'seven-days-al-fatihah',
    title: 'Seven Days, Seven Verses: Living the Message of Al-Fatihah',
    summary: 'Walk through each verse of Al-Fatihah over seven days — reflect, understand, and live the opening of the Quran.',
    days: 7,
    surahNumber: 1,
    imageTone: 'from-violet-700 via-fuchsia-600 to-rose-500',
    featured: true,
  },
  {
    slug: 'surah-al-masad',
    title: 'Surah Al-Masad: A Warning Against Pride',
    summary: 'A short but powerful warning about arrogance, and the consequences of opposing guidance.',
    days: 3,
    surahNumber: 111,
    imageTone: 'from-stone-700 via-amber-800 to-orange-700',
  },
  {
    slug: 'surah-al-kafirun',
    title: 'Surah Al-Kafirun: Sincere and Steadfast',
    summary: 'Learn how to hold firm to faith with clarity, sincerity, and respectful boundaries.',
    days: 4,
    surahNumber: 109,
    imageTone: 'from-slate-700 via-teal-800 to-cyan-700',
  },
  {
    slug: 'surah-al-ikhlas',
    title: 'Surah Al-Ikhlas: The Oneness of Allah',
    summary: 'Discover the essence of Tawhid through one of the most beloved surahs in the Quran.',
    days: 4,
    surahNumber: 112,
    imageTone: 'from-sky-800 via-blue-700 to-indigo-700',
    featured: true,
  },
  {
    slug: 'surah-an-nasr',
    title: 'Surah An-Nasr: When Victory Becomes Farewell',
    summary: 'Reflect on victory, humility, and preparing the heart for the journey’s end.',
    days: 3,
    surahNumber: 110,
    imageTone: 'from-emerald-800 via-teal-700 to-lime-700',
  },
  {
    slug: 'surah-al-falaq',
    title: 'Surah Al-Falaq: Light Before Sunrise',
    summary: 'Seek refuge in Allah from every hidden harm as morning light overcomes darkness.',
    days: 5,
    surahNumber: 113,
    imageTone: 'from-amber-600 via-orange-600 to-rose-500',
  },
  {
    slug: 'surah-an-nas',
    title: 'Surah An-Nas: The Ultimate Refuge',
    summary: 'Learn to turn to Allah as Lord, King, and Protector from whispers that unsettle the heart.',
    days: 5,
    surahNumber: 114,
    imageTone: 'from-indigo-800 via-violet-700 to-purple-600',
  },
  {
    slug: 'surah-al-asr',
    title: 'Surah Al-Asr: The Weight of Time',
    summary: 'Time is running — faith, good deeds, truth, and patience are the way to success.',
    days: 3,
    surahNumber: 103,
    imageTone: 'from-zinc-800 via-stone-700 to-neutral-600',
  },
  {
    slug: 'surah-ash-sharh',
    title: 'Surah Ash-Sharh: The Expansion of the Heart',
    summary: 'Find comfort in Allah’s promise: with every hardship comes ease.',
    days: 4,
    surahNumber: 94,
    imageTone: 'from-rose-700 via-pink-600 to-fuchsia-600',
  },
  {
    slug: 'surah-ad-duha',
    title: 'Surah Ad-Duha: Morning Light, Hope and Gratitude',
    summary: 'When you feel abandoned, this surah renews hope, gratitude, and trust in Allah’s care.',
    days: 5,
    surahNumber: 93,
    imageTone: 'from-yellow-600 via-amber-500 to-orange-500',
  },
  {
    slug: 'surah-al-waqiah',
    title: 'Surah Al-Waqi‘ah: When the Inevitable Event Occurs',
    summary: 'Reflect on the Day of Judgment and the three groups of humanity.',
    days: 7,
    surahNumber: 56,
    imageTone: 'from-cyan-800 via-sky-700 to-blue-800',
  },
  {
    slug: 'surah-ar-rahman',
    title: 'Surah Ar-Rahman: The Surah of Mercy',
    summary: 'Count Allah’s blessings and respond to the recurring call of Ar-Rahman.',
    days: 10,
    surahNumber: 55,
    imageTone: 'from-teal-700 via-emerald-600 to-green-600',
    featured: true,
  },
  {
    slug: 'surah-as-sajdah',
    title: 'Surah As-Sajdah: Prostration & Purpose',
    summary: 'Prostration as a path to purpose — creation, revelation, and the hereafter.',
    days: 7,
    surahNumber: 32,
    imageTone: 'from-blue-900 via-indigo-800 to-slate-800',
  },
  {
    slug: 'surah-al-insan',
    title: 'Surah Al-Insan: The Human, From Nothing to Gratitude',
    summary: 'From a drop to dignity — how gratitude shapes the human journey.',
    days: 7,
    surahNumber: 76,
    imageTone: 'from-fuchsia-800 via-purple-700 to-violet-700',
  },
  {
    slug: 'surah-al-hadid',
    title: 'Surah Al-Hadid: Has the Time Not Come?',
    summary: 'A wake-up call to soften the heart and live with purpose before it is too late.',
    days: 8,
    surahNumber: 57,
    imageTone: 'from-slate-800 via-zinc-700 to-stone-600',
  },
  {
    slug: 'islamic-manners',
    title: 'Islamic Manners: The Prophetic Approach',
    summary: 'Practical manners drawn from the Quran’s guidance for daily character.',
    days: 7,
    searchQuery: 'manners',
    imageTone: 'from-emerald-700 via-teal-600 to-cyan-600',
  },
  {
    slug: 'call-to-hajj',
    title: 'Answering Allah’s Call to Hajj',
    summary: 'Prepare the heart for pilgrimage through Quranic verses about Hajj and devotion.',
    days: 7,
    searchQuery: 'hajj',
    imageTone: 'from-amber-700 via-yellow-600 to-lime-600',
  },
  {
    slug: 'divine-names',
    title: 'Where Allah’s Names Interlock: A Deep Quranic Journey Through Divine Pairings',
    summary: 'Explore how Allah’s names appear together in the Quran and what they teach the heart.',
    days: 14,
    searchQuery: 'Allah',
    imageTone: 'from-indigo-900 via-blue-800 to-cyan-800',
  },
  {
    slug: 'path-to-paradise',
    title: 'The Path to Paradise: Small Consistent Actions That Lead to Jannah',
    summary: 'Small, steady deeds — built from Quranic motivation — that lead toward Paradise.',
    days: 10,
    searchQuery: 'paradise',
    imageTone: 'from-green-800 via-emerald-700 to-teal-600',
  },
  {
    slug: 'family-rights',
    title: 'The Nearest Ties: Quranic Rights of Family',
    summary: 'Honor parents, spouse, and kin through clear Quranic guidance.',
    days: 7,
    searchQuery: 'family',
    imageTone: 'from-rose-800 via-red-700 to-orange-700',
  },
  {
    slug: 'why-tests',
    title: 'Why Allah Tests Us: Finding Strength and Wisdom in Trials',
    summary: 'Learn how trials purify, elevate, and draw the believer closer to Allah.',
    days: 7,
    searchQuery: 'patience',
    imageTone: 'from-stone-800 via-neutral-700 to-zinc-600',
  },
  {
    slug: 'children-salah',
    title: 'Little Hearts, Big Prayers: Raising Children Who Love Salah',
    summary: 'Quranic wisdom for nurturing love of prayer in young hearts.',
    days: 7,
    searchQuery: 'prayer',
    imageTone: 'from-sky-700 via-cyan-600 to-teal-600',
  },
  {
    slug: 'modesty',
    title: 'From Wandering Eyes to a Watchful Heart: The Road Back to Modesty',
    summary: 'Rebuild modesty of the gaze and heart with Quranic guidance.',
    days: 7,
    searchQuery: 'modesty',
    imageTone: 'from-violet-900 via-purple-800 to-fuchsia-700',
  },
  {
    slug: 'surah-yasin',
    title: 'The Heart of the Quran: Lessons from Surah Yā Sīn on Faith, Mercy, and Accountability',
    summary: 'Journey through Ya-Sin — faith, reminders, mercy, and accountability.',
    days: 14,
    surahNumber: 36,
    imageTone: 'from-cyan-900 via-teal-800 to-emerald-700',
    featured: true,
  },
  {
    slug: 'opening-of-the-heart',
    title: 'The Opening of the Heart: Lessons From Surah Al-Fatihah',
    summary: 'A deeper companion plan for understanding Al-Fatihah as a daily conversation with Allah.',
    days: 7,
    surahNumber: 1,
    imageTone: 'from-amber-800 via-rose-700 to-pink-700',
  },
  {
    slug: '30-days-al-mulk',
    title: '30 Transformative Days with Surah Al-Mulk: Learn, Reflect, Memorize',
    summary: 'Spend a month with Al-Mulk — learn its meanings, reflect nightly, and memorize with purpose.',
    days: 30,
    surahNumber: 67,
    imageTone: 'from-indigo-800 via-violet-700 to-purple-600',
    featured: true,
  },
  {
    slug: 'prepare-ramadan',
    title: 'Preparing our Hearts for Ramadan',
    summary: 'Warm the heart before Ramadan with Quranic themes of mercy, fasting, and renewal.',
    days: 14,
    searchQuery: 'ramadan',
    imageTone: 'from-violet-800 via-indigo-700 to-blue-700',
  },
  {
    slug: 'surah-yusuf',
    title: 'When the Stars Prostrated: Reflections on Surah Yusuf',
    summary: 'Patience, trust, and beauty through the story of Prophet Yusuf.',
    days: 14,
    surahNumber: 12,
    imageTone: 'from-yellow-700 via-amber-600 to-orange-600',
  },
  {
    slug: 'surah-al-kahf',
    title: '4 Life-Changing Stories: Lessons From Surah Al-Kahf',
    summary: 'The people of the cave, the two gardens, Musa & Khidr, and Dhul-Qarnayn.',
    days: 14,
    surahNumber: 18,
    imageTone: 'from-emerald-800 via-green-700 to-lime-700',
    featured: true,
  },
  {
    slug: 'marriage-mercy',
    title: 'Created in Pairs: Mercy and Forgiveness in Marriage',
    summary: 'Quranic foundations for mercy, partnership, and healing in marriage.',
    days: 7,
    searchQuery: 'marriage',
    imageTone: 'from-rose-700 via-pink-600 to-fuchsia-500',
  },
  {
    slug: 'islam-of-ibrahim',
    title: 'The Islam of Ibrahim: Walking in the Footsteps of the Friend of Allah',
    summary: 'Sacrifice, trust, and submission through Ibrahim’s Quranic journey.',
    days: 10,
    searchQuery: 'Ibrahim',
    imageTone: 'from-amber-800 via-yellow-700 to-stone-600',
  },
  {
    slug: 'tawakkul',
    title: 'Tawakkul: Trusting Allah in an Age of Anxiety',
    summary: 'Rebuild trust in Allah when worry feels louder than certainty.',
    days: 7,
    searchQuery: 'trust',
    imageTone: 'from-sky-800 via-blue-700 to-indigo-600',
  },
  {
    slug: 'standing-tall',
    title: 'Standing Tall: A Faith‑Based Response to Hate',
    summary: 'Respond to hardship and hostility with dignity rooted in the Quran.',
    days: 7,
    searchQuery: 'patience',
    imageTone: 'from-zinc-800 via-slate-700 to-blue-900',
  },
  {
    slug: 'duas-of-angels',
    title: 'Duas of the Angels in the Quran',
    summary: 'Discover how the angels pray for the believers — and what that means for us.',
    days: 5,
    searchQuery: 'angels',
    imageTone: 'from-cyan-700 via-sky-600 to-indigo-600',
  },
  {
    slug: 'swt-glory',
    title: 'SWT: Allah’s Absolute Glory and Perfection',
    summary: 'Reflect on Allah’s perfection through verses that glorify Him.',
    days: 5,
    searchQuery: 'glory',
    imageTone: 'from-yellow-800 via-amber-700 to-orange-700',
  },
  {
    slug: 'what-is-ihsan',
    title: 'What is Ihsan? Discover the quality that elevates how you live, work, and worship',
    summary: 'Pursue excellence in worship and character as taught in the Quran.',
    days: 7,
    searchQuery: 'ihsan',
    imageTone: 'from-teal-800 via-emerald-700 to-green-600',
  },
  {
    slug: 'am-i-sincere',
    title: '"Am I Sincere?": The Importance of Doing Everything for the Sake of Allah',
    summary: 'Purify intention and realign your deeds for Allah alone.',
    days: 7,
    searchQuery: 'sincere',
    imageTone: 'from-purple-800 via-violet-700 to-fuchsia-600',
  },
  {
    slug: 'cultivate-barakah',
    title: 'How To Cultivate Barakah in a Busy Routine',
    summary: 'Find blessing in time, work, and worship through Quranic habits.',
    days: 7,
    searchQuery: 'blessing',
    imageTone: 'from-lime-700 via-green-600 to-emerald-600',
  },
  {
    slug: 'recitation-to-transformation',
    title: 'From Recitation to Transformation: A 7‑Day Path to Living the Quran',
    summary: 'Move from reading words to living meanings in one intentional week.',
    days: 7,
    surahNumber: 1,
    imageTone: 'from-rose-800 via-red-700 to-amber-600',
  },
  {
    slug: 'guarding-the-tongue',
    title: 'Guarding the Tongue: Protecting the Heart',
    summary: 'Protect speech, heal relationships, and guard the heart with Quranic reminders.',
    days: 7,
    searchQuery: 'tongue',
    imageTone: 'from-slate-800 via-zinc-700 to-neutral-700',
  },
];

export function getLearningPlan(slug: string): LearningPlan | undefined {
  return LEARNING_PLANS.find((p) => p.slug === slug);
}

export function getPlanHref(plan: LearningPlan): string {
  if (plan.surahNumber) return getSurahPath(plan.surahNumber);
  if (plan.searchQuery) return `/search?q=${encodeURIComponent(plan.searchQuery)}`;
  return '/learning-plans';
}
